# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... (sum 231)
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum_of_fibs(n):

    a = 1
    b = 2
    seq = [a,b]
    sum = a + b

    for i in range(1,n-1):
        print(i)
        c = a + b
        a = b
        b = c

        #print(c)
        sum = sum + c
        seq.append(c)


    print(seq)
    print(sum)


# sum_of_fibs(10)


def find_max_terms_under(input):
    
    a = 1
    b = 2
    seq = [a,b]
    sum = a + b
    c = 0

    while a+b < input:
        c = a + b
        a = b
        b = c

        sum = sum + c
        seq.append(c)


    # print(seq)
    # print(sum)
    # print(len(seq))

    evenseq = []
    evenseqsum = 0

    for number in seq:
        if number % 2 == 0:
            evenseqsum = evenseqsum + number
            evenseq.append(number)

    print(evenseqsum)



find_max_terms_under(4000000)